version: "3"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "redis:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 5
      timeout: 3s

volumes:
  redis:
    driver: local

# volumes:
#   mysql_data:
